env:
  global:
    secure: "A6kZ/KYJXpR1xHuifFSUo8qSpDvXVcBlABQrtd39a09KMaUAWClcp17SM2l3ehMDufWgvkHBBl3MGJaV6dS+H8n2DYOIHjdLYoiFTRccNcQgS7ES/WKNABYLHeqh1jT21E/ttSFUAWIqRbKkzeji45yAiq58YVT/G6+P0cNwiEzkcO1bhCyEMAiU9dCupaQL59wzK+vpmTHnjqSnpdBaxE1f/AFdbNV/bCesQv4xisFUbEVPuYLFZ260Leu5IPJm9mNvB0su1qK2jxxYdMIGakMB9s+amOFOt1Hd3cetrWQi8vQonsOOlMLpJEMkIb+NDJT8K4ot8vBzNrUx/HWKcAHLM29FxcLuBD7WTNGr02SUOtx4oP5wAohMhqRD/v9V4tWwsCVIrOuYYQLxh/FIvrws7c2pB+FwYVvPHtsSSz5/hOD6pec/lW0DZjLqmGo3g76YczxxO9mrzSwgEhRRJPlyVzrEEeBihVrpdZBRe3vxMOLLr/3qrZXFb0G3KTt+IZj6fGssyTVJ+Pi5fJtquumetZfI9lL0OmkHTrxeowAWB7Zvdxnc4czW4nQDDGTOBDO9haInDGFhXtKvSILokUHDVlRDJbbimSQi99yiSSZMdvM5uLSDlCDbx3JXwA4Ha/s2Cgc6V3CfuVM9js94g+2sopyTu7f567KoqjQrLd8="

before_install:
  - eval "${MATRIX_EVAL}"

dist: xenial
language: c
script: ./build.sh

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
      env:
        - MATRIX_EVAL="CC=gcc-8"

addons:
  apt:
    update: true
